// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nypdvlznczkntvfyywlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cGR2bHpuY3prbnR2Znl5d2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzODkzNzgsImV4cCI6MjA3Njk2NTM3OH0.WMyLOB52DPYJJXQd7ix7mg6DjnWcCkYTN68NKAPjNcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});